### ISSUE TITLE
Renaming pages - causing error

### ISSUE THREAD

**Issue by valeriegibson** [kipusoep/UrlTracker#93] opened 2015-09-30 14:05 UTC
Hello,

When a page is renamed automatically, it throws an error on the redirect

![capture](https://cloud.githubusercontent.com/assets/528423/10195239/80ca7fc6-6784-11e5-9256-39cf0826eca2.PNG)

If we go in and save it with "force redirect" on and resave it, then the error goes away and the redirect works again.

Help... :(

**Comment by kipusoep** [comment] 2015-09-30 14:08
That's weird, the exception is thrown inside umbraco, not inside the UrlTracker.
It's not possible for me to determine what's going on without a way to reproduce/debug this.

You are using the latest version?

**Comment by valeriegibson** [comment] 2015-09-30 14:26
7.3 yep with the latest Url Tracker. 

To reproduce, create a page e.g MyPage
rename page e.g MyNewPage
when going to /mypage the redirect to /mynewpage will not work and will throw the error.

**Comment by kipusoep** [comment] 2015-09-30 15:31
Seems like a 7.3 issue: https://our.umbraco.org/projects/developer-tools/301-url-tracker/version-2/44327-Issues-with-URL-Tracker-in-614
I'll look into it, but it will take at least 4 weeks (holiday).

**Comment by kipusoep** [comment] 2015-10-01 07:05
Duplicate of #90

**Closed by kipusoep** 2015-10-01 07:05 UTC
