### ISSUE TITLE
iCurlTracker sql command causes high DTU(100%) usage

### ISSUE THREAD

**Issue by blevai13** [kipusoep/UrlTracker#169] opened 2017-09-21 18:26 UTC
Hi,

Can somebody give me some hints why this sql command (@0 int,@1 int)SELECT * FROM icUrlTracker WHERE Is404 = 0 AND ForceRedirect = @0 AND (RedirectRootNodeId = @1 OR RedirectRootNodeId = -1) AND OldRegex IS NOT NULL ORDER BY Inserted DESC
causes to hit the ceiling for datbase DTU.
The database usage was maximum till I stopped and restarted the IIS service. 

Any information/suggestion would be much appreciated!
Thanks,

**Comment by kipusoep** [comment] 2017-09-21 18:27
Maybe there are many records, how many are there inside the icUrlTracker table?

**Comment by blevai13** [comment] 2017-09-21 18:30
hi @kipusoep,

Actually no, I mean 21841 it's not that much to cause such a problem I think. Any other hints, I didn't look in the code, but can you tell me when this command is called to be executed?
Thanks

**Comment by blevai13** [comment] 2017-09-21 18:43
(@0 int,@1 nvarchar(4000),@2 nvarchar(4000))SELECT * FROM icUrlTracker WHERE Is404 = 0 AND ForceRedirect = 0 AND (RedirectRootNodeId = @0 OR RedirectRootNodeId IS NULL OR RedirectRootNodeId = -1) AND (OldUrl = @1 OR OldUrl = @2) ORDER BY CASE WHEN RedirectHttpCode = 410 THEN 2 ELSE 1 END, OldUrlQueryString DESC

This command was also involved causing high DTU

**Comment by kipusoep** [comment] 2017-09-21 20:25
Don't know, we have 15 ~ 20 websites with the UrlTracker running on Azure and haven't run into this yet.

**Comment by blevai13** [comment] 2017-09-22 06:11
It's really frustrating since yesterday when I've upgrade we are facing with this issue, and over the night the DTU from hour to hour was increased. Another info we have 2 servers in load balancing in azure and a master server.
Although we have a small table like I mentioned before I don't think this is normal, somehow the command gets executed too many times or likely something is wrongly initialized - the records like increasing in memory?(after you read them out from the table) and then doesn't get cleaned,released so at the next read the object will increase... I don't know but for sure this new version 3.13.1 is bugy... unfortunetaley with the old version the redirects doesn't work... so I think we might need for another plugin/solution if this won't be fixed.
Thanks

**Comment by daniel-chenery** [comment] 2017-09-22 06:59
I think this is a potential duplicate of #166, and I'm hoping it's a mix-up between ISQLHelper and DatabaseContext

However, if you run that actual SQL query on your database via SSMS, how long does it take to execute?
21,000+ is a lot of entries for a database table...

**Comment by blevai13** [comment] 2017-09-22 07:06
Hi @daniel-chenery,

I have just run the sql command and it takes about 5 seconds. But the problem is not with the execution time, in fact this command gets executed more and more time(it seems like from performance query insight) the number of execution on this increasing hourly. So I think may this is related to one of your comment with the umbraco endrequest and probably the HttpModule getting loaded too many times(wrongly) since we have load balancing(we have 2 FE server and one master) working with the same database..
Any solution/suggestion would be much appreciated. We are on production in this is affecting potentially our client and the users of the site.
Thanks

**Comment by daniel-chenery** [comment] 2017-09-22 07:10
@blevai13 If it's not the execution time slowing it down (I must have misread), it must be the EndRequest issue.

I have been looking into it this week, trialing different things
I will push a patch when I have one :(

**Comment by blevai13** [comment] 2017-09-22 07:12
Many thanks, I'll follow your updates.

**Comment by blevai13** [comment] 2017-09-22 07:24
@daniel-chenery 
Just a hint, might be help coulndn't you check somehow if the httpmodule was registered before and if yes just remove and then add it again, or don't add at all second time?

Some related info [here]([url](https://stackoverflow.com/questions/24793525/exception-when-registering-unityperrequesthttpmodule-with-mvc-5)).

**Comment by daniel-chenery** [comment] 2017-09-22 07:48
@blevai13 That's what I'm trying to do.

The old method of locks doesn't work it just YSOD's, and I can't remove my Event since the Umbraco module has also been restarted and lost my reference :(

The code that article refers to though is already in

**Comment by blevai13** [comment] 2017-09-23 22:18
Hi @daniel-chenery,

I hope I may solved the problem at least in our case, it seems definitely not a good idea to hook up the UrlTrackerModule to Umbraco Endrequest event. It seems like Umbraco Core has some serious bug, because in the background process it just screwed up some documents and creating new versions making periodically save and publish, this is another big problem we are facing, because it's increasing the database size, but this seems like having side effect also on UrlTracker behavior when this plugin is hooked up to Umbraco Endrequest.
I'm not sure what's going for sure I'm just guessing that could cause the problem, I also don't understand why some of the documents getting saved and published by the background umbraco process.... anyway maybe would be better to find some other way to trigger the UrlTrackerDo, because as you can see you can not count on Umbraco Core that's working 100% as you expected. Maybe, maybe some page not found event triggered in the back or something similar(404) and there should be called the redirect process(UrlTrackerDo).
I'm looking forward to hearing from new updates here :). Thanks
Regards,

**Comment by daniel-chenery** [comment] 2017-09-26 07:57
@blevai13 Should be fixed with the latest BETA version (3.14), let me know if the problems are still there though

**Closed** 2017-11-11 13:15 UTC
