### ISSUE TITLE
Redirects are always 302

### ISSUE THREAD

**Issue by Elijha** [kipusoep/UrlTracker#72] opened 2015-03-27 01:20 UTC
While the redirect seems to work fine in all cases I always see a 302 (temporary) redirect not a 301 (permanent). I have tried with and without the force redirect option.

I discovered this in version 3.4 and have upgraded to 3.6 and it still persists. 
Umbraco version 7.2.1 assembly: 1.0.5462.37503

I'm not sure what other details you might need - but ask and I will supply if possible.

**Comment by kipusoep** [comment] 2015-05-22 14:28
I can't reproduce this, are you sure it's still the same with v3.8?

**Comment by kipusoep** [comment] 2015-11-27 15:28
No reply, so closing.

**Closed by kipusoep** 2015-11-27 15:28 UTC
