### ISSUE TITLE
Redirects made in 404 View are not listed in URL Tracker View

### ISSUE THREAD

**Issue by KirschnerMatt** [kipusoep/UrlTracker#64] opened 2015-02-19 14:08 UTC
I love that URL Tracker lists pages that resulted in a 404 and, even better, allows me to create a redirect from the same view. However, I noticed that when I create a redirect from the 404 view, the record is removed but is not added to the 301 Tracker View as I would expect. I've confirmed that the redirect does still work, but I'm unable to edit it since it won't appear in the view. Has anyone else experienced this?

I'm using Umbraco 7.2.1 on an NLB with UrlTracker 3.3

**Comment by kipusoep** [comment] 2015-02-19 14:19
NLB = load balancing?

**Comment by KirschnerMatt** [comment] 2015-02-19 14:25
Yes, Microsoft's load balancing software. It took some [extra setup] (https://our.umbraco.org/documentation/Installation/load-balancing) to get Umbraco working in this environment so I figured it might be relevant.

**Comment by kipusoep** [comment] 2015-02-20 09:37
I can't reproduce this, so I'd say this has got something to do with the LB environment.
I'm not sure what might cause this and I don't have a LB environment ready for me to test.

**Comment by kipusoep** [comment] 2015-11-27 15:30
No reply, so closing.

**Closed by kipusoep** 2015-11-27 15:30 UTC
