### ISSUE TITLE
Bulk Url Import Activation

### ISSUE THREAD

**Issue by KeironM** [kipusoep/UrlTracker#197] opened 2018-12-10 11:27 UTC
Hi Stefan

Firstly thanks for this great plug-in!

Only issue I'm experiencing is activating a large number of redirects that I've just imported into the Database table.

I've done a bulk insert (over 1,000) and although they're appearing correctly in the backoffice, they don't actually work. I've tried restarting the site/recycling app pools but this has no affect. It does work however when I manually go into the backoffice and save one of the new redirects but ideally I want to avoid doing that for all of them.

Is there a method that I'm missing here?

Any help would be appreciated.

Keiron

**Comment by daniel-chenery** [comment] 2018-12-10 11:34
This is a duplicate of #145, so I'll close straight away (I'll admit, it's not an obvious duplicate title)

I really am unsure of the issue though, like I said, all I can suggest to you is enable logging and see where it falls over.
Failing that, you could clone the plugin locally and step-through. This will allow you to check if your SQL-inserted route has made in inside the cache.

**Closed by daniel-chenery** 2018-12-10 11:34 UTC
