### ISSUE TITLE
NullReferenceException with 7.3 Beta 3 and Multiple root nodes 

### ISSUE THREAD

**Issue by JBoye** [kipusoep/UrlTracker#90] opened 2015-08-11 15:16 UTC
I get the following exception on all 404 pages. It can be reproduced by installing a clean 7.3 Beta 3, and create multiple root nodes

    [NullReferenceException: Object reference not set to an instance of an object.]
    Umbraco.Web.Routing.DefaultUrlProvider.GetUrl(UmbracoContext umbracoContext, Int32 id, Uri current, UrlProviderMode mode) +243
    Umbraco.Web.Routing.<>c__DisplayClass3.<GetUrl>b__0(IUrlProvider provider) +49
    System.Linq.WhereSelectArrayIterator`2.MoveNext() +110
    System.Linq.Enumerable.FirstOrDefault(IEnumerable`1 source, Func`2 predicate) +214
    Umbraco.Web.Routing.UrlProvider.GetUrl(Int32 id, Uri current, UrlProviderMode mode) +235
    InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.UrlTrackerDo(String callingEventName, Boolean ignoreHttpStatusCode) in d:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:178
    System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +160
    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +164

**Comment by JBoye** [comment] 2015-08-12 07:48
Complete project: http://upload.lindberg.pro/9wqpn/umbracocms730-beta3.zip

**Comment by kipusoep** [comment] 2015-08-13 07:20
Thanks, I'll look into this, I think tomorrow :-)

**Comment by nul800sebastiaan** [comment] 2015-08-13 16:09
I've had a look at it and the null reference is umbracoContext here, even though you're "ensuring" the context (which made Shannon nervous when I asked him about it). But it's out of my league to debug fully.

**Comment by kipusoep** [comment] 2015-08-13 16:34
Hmm, @nul800sebastiaan you looking into this issue, does that mean you're having the same issue on our umbraco?

**Comment by nul800sebastiaan** [comment] 2015-08-13 17:08
Nope, I only have one domain set on Our. Just looking to see what we broke in Umbraco (if anything).

**Comment by kipusoep** [comment] 2015-10-01 07:30
So it seems UmbracoContext.Application is null, which is weird because ApplicationContext.Current is set and usable.
Seems like a breaking change in Umbraco and maybe even a bug?
What do you think @nul800sebastiaan ?

**Comment by JBoye** [comment] 2015-10-06 15:04
Just to confirm, @nul800sebastiaan's PR fixes the issue for me

**Comment by shearer3000** [comment] 2015-11-04 19:20
hi - will this be released soon? :D

**Comment by kipusoep** [comment] 2015-11-04 19:23
I'll test again Friday and hopefully release an update! Apologies for the delay!

**Comment by shearer3000** [comment] 2015-11-04 19:24
no worries. thanks!

**Comment by shearer3000** [comment] 2015-11-16 22:24
hi - is there any scheduled release in mind yet? thanks

**Comment by kipusoep** [comment] 2015-11-16 22:33
Yes, I fixed it today and will release an update tomorrow.

**Comment by kipusoep** [comment] 2015-11-17 08:12
Just released 3.10-rc. I need some help testing it before marking it as stable.
It's available on NuGet: https://www.nuget.org/packages/UrlTracker/3.10.0-rc

Please help me test this :-)

**Comment by engern** [comment] 2015-11-18 12:07
Just tested it on my 7.3.0 and seems to work just fine. I have created manually and from 404 view. Both 301 and 302.  Regex is like Greek to me, so I have not tested that. Force redirect works. Querystring works. Great job :+1:

**Comment by kipusoep** [comment] 2015-11-18 12:40
Thanks @engern for testing and creating an account just for this comment ;-)

**Comment by nul800sebastiaan** [comment] 2015-11-18 12:42
Haven't had time to test, just one scenario I just thought of: does it handle `.html`? So say your old said had some html files you want to redirect, does that work properly with this version?

**Comment by kipusoep** [comment] 2015-11-18 12:44
Dammit! It doesn't :-( Now I remember why I used an HttpModule...
So now what?

Ps. Thanks for the heads-up, didn't thought about that scenario.

**Comment by nul800sebastiaan** [comment] 2015-11-18 13:30
Yeah, I just realized that contentfinders don't handle "static" files. I'll have a chat with Shannon to see what else we can do.

**Comment by kipusoep** [comment] 2015-11-18 13:39
Please do, I'm out of options.

**Comment by ZNS** [comment] 2015-11-18 14:53
I'm looking into this issue also. In 7.3.1 UmbracoContext.Security is still disposed on EndRequest. This causes UmbracoContext.Current.UrlProvider.GetUrl() to throw an exception. The problem is that it doesn't seem possible to catch certain requests (mainly for static files) on any other event than EndRequest. At least not after that Umbraco has handled the request. I've tried PostReleaseRequestState and UpdateRequestCache and neither fires.

**Comment by nul800sebastiaan** [comment] 2015-11-18 15:54
So, you were right @kipusoep - the `response.End()` in `PublishedContentNotFoundHandler` causes the `PostRequestHandlerExecute` event to not be fired. We'll remove it for 7.3.2.

Question is though.. how were you ever handling `.html` (etc.) files before? We don't create an Umbraco context for static files so I'm not sure how that worked before.

So: for non-static files you can use `PostRequestHandlerExecute` in 7.3.2 and the GetUrl call should succeed.
For static files you'd still subscribe to the `EndRequest` event and do what you did before I guess? I just don't know how you managed to get a Url from this before.

**Comment by kipusoep** [comment] 2015-11-18 15:56
@nul800sebastiaan I know a few things about HttpModules and Response.End() etc. ;-)
An HttpModule gets executed for every request, also for .html requests, so that's how I handle them, easy as that :-)
So back to an HttpModule it is, glad this is being fixed in 7.3.2!

**Comment by nul800sebastiaan** [comment] 2015-11-18 19:03
You can give it a go with the latest nightly (build 110): http://nightly.umbraco.org/?container=umbraco-730

**Comment by avatart0ph** [comment] 2015-11-24 01:40
was wondering if i can still download RC v3.10?

**Comment by avatart0ph** [comment] 2015-11-24 02:41
kinda need this fix or we cant upgrade to 7.3.1. Is there any update to this?

**Comment by kipusoep** [comment] 2015-11-24 08:47
@avatart0ph You can use the RC which works with 7.3.0 and 7.3.1.
The only issue is with non-asp.net URL's, like .html and .php.
For 7.3.2 I'll have to create a new release.

**Comment by akeilox** [comment] 2015-11-24 08:57
@kipusoep can I  clarify, for users on 7.1 if I download the latest source and compile, the non-asp.net URLs will be working?
I normally download the source and edit the info page/tabs (with text and internal links that editors can read further) instead of installing from the package.
Would appreciate if you can clarify.

**Comment by kipusoep** [comment] 2015-11-24 09:03
For 7.1 you don't need the RC, just go for 3.9 :-)

**Comment by akeilox** [comment] 2015-11-24 09:07
Thanks!

**Comment by avatart0ph** [comment] 2015-11-24 18:27
@kipusoep thank you. unfortunately, we will have to wait for 7.3.2 >_< already skipped 7.3.0 and now this version cause we need your plugin to work.

why is it that when umbraco upgrades some plugins dont work anymore?
that has been our biggest (and most frustrating) issue with umbraco thus far. we have to retest everything. this is very unfortunate.

**Comment by nul800sebastiaan** [comment] 2015-11-24 19:05
We're not perfect, sometimes we accidentally break things (like this) and then we try hard to come up with a solution (like for this problem). :-)

**Comment by kipusoep** [comment] 2015-11-24 19:15
It's hard, if not impossible, to think of all possible consequences with every code change. So cut them some slack please :-)

**Comment by avatart0ph** [comment] 2015-11-24 21:51
@nul800sebastiaan @kipusoep I apologize. no one is perfect. its just hard being the 'man in the middle' and i cant control some things. i love umbraco and have just started contributing to other projects (if i have tested it in a working environment and no issues from client for months). I guess umbraco just needs some sort of control to the plugins?

**Comment by kipusoep** [comment] 2015-11-24 21:53
We're all part of this community and everybody needs to help by fixing 3rd party plug-in issues and umbraco issues, that's the great thing about open-source software :-)
As I said; you can use the UrlTracker RC for Umbraco 7.3.0 and 7.3.1, automatic redirects will still work, just not .html/.php requests. But maybe you do have redirects for those extensions?

**Comment by avatart0ph** [comment] 2015-11-24 21:55
@kipusoep yeah i do. php and html. lol.:)

**Comment by kipusoep** [comment] 2015-11-24 21:57
Ah, I'm sorry about that. Then you'll just have to wait for 7.3.2, can't take long I guess. Do you have a planned release date @nul800sebastiaan? So I can have a working and tested release ready before the release?

**Comment by kipusoep** [comment] 2015-11-26 15:52
Ok so it seems 7.3.2 is release just now. I'm sorry, but I don't have an update UrlTracker release yet. Hopefully tomorrow.

**Comment by nul800sebastiaan** [comment] 2015-11-26 16:09
Ah sorry, forgot to update this ! We weren't quite sure if we would be able to release this week :-)

**Comment by kipusoep** [comment] 2015-11-27 14:42
I just tested the new PostRequestHandlerExecute with Umbraco 7.3.2, but it's not getting executed when I request "/test.html". EndRequest is getting executed though.
I'm just not sure why this is happening. :-(

**Comment by kipusoep** [comment] 2015-11-27 14:44
Fuuuuuuuu: Occurs when the ASP.NET event handler (for example, a page or an XML Web service) finishes execution.

**Comment by nul800sebastiaan** [comment] 2015-11-27 15:10
Yeps, that's what I was trying to say here, you'll need to use both: 

> So: for non-static files you can use PostRequestHandlerExecute in 7.3.2 and the GetUrl call should succeed.
> For static files you'd still subscribe to the EndRequest event and do what you did before I guess? I just don't know how you managed to get a Url from this before.

**Comment by kipusoep** [comment] 2015-11-27 15:24
It seems I don't have to change a thing; just using EndRequest works again like it used to, so 3.9 will just work :-)

**Comment by nul800sebastiaan** [comment] 2015-11-27 16:33
Ah yes.. I think that should work! :-)

**Comment by JBoye** [comment] 2015-11-30 13:37
I tried to upgrade Umbraco to 7.3.2 and downgraded Url tracker to 3.9, but now I'm getting these again on a 404 request:

[NullReferenceException: Object reference not set to an instance of an object.]
   Umbraco.Web.Routing.DefaultUrlProvider.GetUrl(UmbracoContext umbracoContext, Int32 id, Uri current, UrlProviderMode mode) +262
   Umbraco.Web.Routing.<>c__DisplayClass3.<GetUrl>b__0(IUrlProvider provider) +47
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +109
   System.Linq.Enumerable.FirstOrDefault(IEnumerable`1 source, Func`2 predicate) +121
   Umbraco.Web.Routing.UrlProvider.GetUrl(Int32 id, Uri current, UrlProviderMode mode) +259
   InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.UrlTrackerDo(String callingEventName, Boolean ignoreHttpStatusCode) in d:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:178
   InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.context_EndRequest(Object sender, EventArgs e) in d:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:81
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +148
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +97

**Comment by JBoye** [comment] 2015-11-30 13:53
Reproduced in 7.3.2 + Url Tracker 3.9:

http://upload.lindberg.pro/8g7il/732.zip
user: admin
pass: testtest

**Comment by kipusoep** [comment] 2015-12-03 10:03
Yeah me too, I thought it worked but it doesn't :-(
So the question is; what changed in Umbraco 7.3 that kills the UrlTracker's ability to get a Node's url in the EndRequest handler?

**Comment by danimalx** [comment] 2015-12-03 15:01
We are getting this error under these circumstances in a load balanced (new method) environment on 7.3.3:

Go to a non-existant page which should give a nice 404 page on a sub directory on the LB domain.

If the page is accessed directly on each of the web servers it's fine. If it's accessed in the root it's fine. e.g.

http://www.loadbalanced.com/xxx/page-does-not-exist - 404 page does not work
http://www.loadbalanced.com/page-does-not-exist - 404 page works

http://www.web1.com/xxx/page-does-not-exist - 404 page works
http://www.web2.com/xxx/page-does-not-exist - 404 page works
http://www.web1.com/xxx/page-does-not-exist - 404 page works
http://www.web2.com/xxx/page-does-not-exist - 404 page works

**Comment by shearer3000** [comment] 2015-12-07 20:42
hi - what is the current status of this ticket? The main umbraco use-case of redirecting an old node url to its new url doesn't work for me on 7.3.2 and urlTracker 3.9

**Comment by shearer3000** [comment] 2015-12-07 20:43
Is there any more info and/or testing I can help with?

**Comment by kipusoep** [comment] 2015-12-07 20:43
I don't know what to do.
@nul800sebastiaan said to me on Twitter:
> Haven't had any time mate, sorry! @Shazwazza is on holiday. I'll look when I get a chance.

**Comment by danimalx** [comment] 2015-12-08 09:01
I appreciate you are busy but because your package is so good it's also essential for anyone wanting to upgrade to 7.3 - it really should be part of the core IMHO. I think we'd all be very happy if it was made compatible with 7.3

**Comment by kipusoep** [comment] 2015-12-08 09:06
@danimalx This has got nothing to do with me being busy anymore. I don't know what to do to fix this...
Also some of the Url Tracker features will be transferred to the core in the near future (scheduled for v7.5) :-) (source: https://onedrive.live.com/view.aspx?resid=4904432BE890F1F8!18961&app=PowerPoint&authkey=!AEm9CThFw42FZNw)

**Comment by SelectUX** [comment] 2015-12-10 02:21
I've stepped into the URLTracker code and it seems the Umbraco method UrlName (on the Node) is failing from Umbraco v7.3.2+ due to a threading issue. I.e. when viewing the Umbraco IPublishedContent in VS debugger you see the following message when accessing UrlName: _"The function evaluation requires all threads to run."_ 

This message also appears on a number of other properties so clearly the core has changed somehow.

As a workaround I have used the Node *"Path"* to create the URL structure for the node. This only resolves the issue around redirects not working for moved nodes or manually created redirects failing. That however, for our projects at least, is by far the most critical issue here.

There is a Pull Request for this change if anybody wants to grab the code or if you want to add it to the current version for now @kipusoep.

**Comment by nul800sebastiaan** [comment] 2015-12-10 10:24
Okay, it looks like I missed the revert of this PR: https://github.com/kipusoep/UrlTracker/pull/97/files

Have you tried handling BOTH `EndRequest` and `PostRequestHandlerExecute`? 

I'll repeat myself again here ;-)

> So: for non-static files you can use PostRequestHandlerExecute in 7.3.2 and the GetUrl call should succeed.
> For static files you'd still subscribe to the EndRequest event and do what you did before I guess? I just don't know how you managed to get a Url from this before.

**Comment by kipusoep** [comment] 2015-12-10 10:25
> For static files you'd still subscribe to the EndRequest event and do what you did before I guess? I just don't know how you managed to get a Url from this before.

This is not going to work, because the NiceUrl won't function in the EndRequest event.

**Comment by nul800sebastiaan** [comment] 2015-12-10 10:33
Would there be a way you to that says to `EndRequest`: "Hey you `EndRequest` handler, don't bother, I've already handled this in `PostRequestHandlerExecute` and you don't need to look any further?"

**Comment by ZNS** [comment] 2015-12-10 10:34
Just giving my two cents worth here. Due to this issue but also other unadressed issues with this otherwise great plugin. We've decided to write our own. We've got it working in 7.3.2 with ordinary requests hooking up to PostRequestHandlerExecute and to EndRequest for static requests, as Sebastiaan suggests. As he also suggest we do set a HttpContext-Item to make sure we don't run both on PostRequestHandler and EndRequest. However in EndRequest the UmbracoContext is always null so we have to execute EnsureContext for it to work. It's only run on 404 static requests so shouldn't be a big problem. However we do not use any legacy dependencies as it seems Url Tracker does, so not sure of how much use this is. Just trying to help out :)

**Comment by kipusoep** [comment] 2015-12-10 10:48
@ZNS 
> also other unadressed issues with this otherwise great plugin
Which issues do you refer to?

> It's only run on 404 static requests so shouldn't be a big problem.
So static requests can't get redirected to a Node's URL, just like the issue we're discussing here?

**Comment by ZNS** [comment] 2015-12-10 10:54
@kipusoep 
Mainly this issue: https://github.com/kipusoep/UrlTracker/issues/84

Yes, our module works for static requests also. As long as we ensure the umbraco context in EndRequest. We use UmbracoContext.Current.UrlProvider.GetUrl(nodeId) to get url for page.

**Comment by kipusoep** [comment] 2015-12-10 10:55
Hmmm that's interesting. That might just work, I'll have a look at it tomorrow hopefully.

**Comment by StephenPAdams** [comment] 2015-12-11 05:09
@kipusoep Checking Force Redirect on any 301 redirects fixes this issue for me on Umbraco 7.3.1 with 3.9 installed. What about checking that allows it to work versus having it unchecked?

**Comment by kipusoep** [comment] 2015-12-11 05:59
That's not an option. The Url Tracker will redirect before Umbraco has a
chance of showing content.

Op 11 dec. 2015 om 06:09 heeft Stephen Adams <notifications@github.com> het
volgende geschreven:

@kipusoep <https://github.com/kipusoep> Checking Force Redirect on any 301
redirects fixes this issue for me on Umbraco 7.3.1 with 3.9 installed. What
about checking that allows it to work versus having it unchecked?

—
Reply to this email directly or view it on GitHub
<https://github.com/kipusoep/UrlTracker/issues/90#issuecomment-163842660>.

**Comment by kipusoep** [comment] 2015-12-11 08:59
@ZNS 
I still get a NullReferenceException:

<pre>[NullReferenceException: Object reference not set to an instance of an object.]
   Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.DetermineRouteById(UmbracoContext umbracoContext, Boolean preview, Int32 contentId) +61
   Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.GetRouteById(UmbracoContext umbracoContext, Boolean preview, Int32 contentId) +86
   Umbraco.Web.Routing.DefaultUrlProvider.GetUrl(UmbracoContext umbracoContext, Int32 id, Uri current, UrlProviderMode mode) +96
   Umbraco.Web.Routing.<>c__DisplayClass3.<GetUrl>b__0(IUrlProvider provider) +28
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +58
   System.Linq.Enumerable.FirstOrDefault(IEnumerable`1 source, Func`2 predicate) +94
   Umbraco.Web.Routing.UrlProvider.GetUrl(Int32 id, Uri current, UrlProviderMode mode) +169
   Umbraco.Web.Routing.UrlProvider.GetUrl(Int32 id) +15</pre>

**Comment by ZNS** [comment] 2015-12-11 10:13
@kipusoep 
Well, pretty sure you get this error because UmbracoContext.Current.Application is null. Here's the code we use to ensure the context if it's null. Note that ensuring the context in EndRequest didn't work for us in 7.3.1 because it got disposed right away. In 7.3.2 this has been working though, haven't tested in 7.3.3 yet.

```
var contextBase = new HttpContextWrapper(HttpContext.Current);
UmbracoContext.EnsureContext(contextBase,
ApplicationContext.Current,
new WebSecurity(contextBase, ApplicationContext.Current),
UmbracoConfig.For.UmbracoSettings(),
UrlProviderResolver.Current.Providers,
false);
```

**Comment by Shazwazza** [comment] 2015-12-14 10:26
What I'm not understanding is the need for UmbracoContext in the EndRequest?

Anything that needs to check against an ASP.Net handled request (i.e. Umbraco), the logic should exist in the PostRequestHandlerExecute  which has the UmbracoContext available. 

Whatever logic is actually being done in EndRequest should not have to access the UmbracoContext. For redirects that are tracked to managed ASP.Net requests - use PostRequestHandlerExecute. For redirects that are tracked for non managed ASP.Net requests (i.e. static files - from what I understand, this package tracks those), - you can use EndRequest.

EnsureContext should be a last option, this should not need to be used in this situation. Further more you should always ensure that you dispose of the UmbracoContext that is returned from EnsureContext.

**Comment by Shazwazza** [comment] 2015-12-14 10:34
Ok, so Sebastiaan has told me that this package tracks some static mappings, such that someone might want to redirect a non handled ASP.Net page like blah.php -> Umbraco node 1234. In this situation, EndRequest will execute but PostRequestHandlerExecute will not because .php is not a handled request, just like .js or .css or other client side files are not handled requests. In all of these situations, an UmbracoContext will probably not even be available anyways because an UmbracoContext is generally only created for managed requests (there will be some exceptions to this norm).

So this is what needs to happen:

* If it is a managed request -> This will happen when PostRequestHandlerExecute executes and there will be an UmbracoContext -> Do all of the work you require here with the UmbracoContext. Then you can store whatever result you want into HttpContext.Items which you can check for in EndRequest
* In EndRequest -> Check if the HttpContext.Items data is available for you to use (= this was a managed request), and use it. If this data is not available then you know it is a non managed request and in this scenario an UmbracoContext is probably not available anyways. So here's what you do:
** Check if UmbracoContext.Current != null, if it's not null then use it.
** If it is null then you can use EnsureContext -> making sure that you use the returned UmbracoContext from this method and put it in a using block so that it's disposed.

**Comment by kipusoep** [comment] 2015-12-14 12:57
Thanks @Shazwazza for clearing things up a bit :-)
Though when I use this piece of code:

```csharp
var contextBase = new HttpContextWrapper(HttpContext.Current);
using (var context = UmbracoContext.EnsureContext(contextBase, ApplicationContext.Current, new WebSecurity(contextBase, ApplicationContext.Current), UmbracoConfig.For.UmbracoSettings(), UrlProviderResolver.Current.Providers, false))
{
    return context.PublishedContentRequest.RoutingContext.UrlProvider.GetUrl(nodeId);
}
```
I get a NullReference Exception:

<pre>[NullReferenceException: Object reference not set to an instance of an object.]
   Umbraco.Web.Routing.DefaultUrlProvider.GetUrl(UmbracoContext umbracoContext, Int32 id, Uri current, UrlProviderMode mode) +208
   Umbraco.Web.Routing.<>c__DisplayClass3.<GetUrl>b__0(IUrlProvider provider) +28
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +58
   System.Linq.Enumerable.FirstOrDefault(IEnumerable`1 source, Func`2 predicate) +94
   Umbraco.Web.Routing.UrlProvider.GetUrl(Int32 id, Uri current, UrlProviderMode mode) +169
   Umbraco.Web.Routing.UrlProvider.GetUrl(Int32 id) +15
   InfoCaster.Umbraco.UrlTracker.Helpers.UmbracoHelper.GetUrl(Int32 nodeId) in D:\kipusoep\Documents\GitHub\UrlTracker\Helpers\UmbracoHelper.cs:140
   InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.LoadUrlTrackerMatchesFromDatabase(HttpRequest request, String urlWithoutQueryString, Boolean urlHasQueryString, String shortestUrl, Int32 rootNodeId, String& redirectUrl, Nullable`1& redirectHttpCode, Boolean& redirectPassThroughQueryString) in D:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:412
   InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.UrlTrackerDo(String callingEventName, Boolean ignoreHttpStatusCode) in D:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:199
   InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.context_EndRequest(Object sender, EventArgs e) in D:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:81
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69</pre>

**Comment by JBoye** [comment] 2015-12-14 14:27
@kipusoep for static files, would a workaround like this work?

"OldFile.js" > 301 redirect to "UrlTracker.aspx?file=OldFile.js" > 301 redirect to "NewFile.js"?

**Comment by kipusoep** [comment] 2015-12-14 14:29
No that's not a final solution I can cope with.

**Comment by kipusoep** [comment] 2015-12-15 19:43
After some debugging I've found the NullReference to be on this line:
```var domainHelper = new DomainHelper(umbracoContext.Application.Services.DomainService);```

It's on this line: https://github.com/umbraco/Umbraco-CMS/blob/d50e49ad37fd5ca7bad2fd6e8fc994f3408ae70c/src/Umbraco.Web/Routing/DefaultUrlProvider.cs#L63

**Comment by ZNS** [comment] 2015-12-16 18:51
@kipusoep 
This was my conclusion also for 7.3.1
https://our.umbraco.org/projects/developer-tools/301-url-tracker/version-2/44327-Issues-with-URL-Tracker-in-614

If you debug further you can check when the UmbracoContext gets disposed. In 7.3.1 it got disposed in EndRequest even if I tried to ensure it. I haven't had that issue since 7.3.2 though.

**Comment by Shazwazza** [comment] 2015-12-17 10:30
@kipusoep When you EnsureContext, this is just creating an UmbracoContext, you are getting a null ref exception because: `context.PublishedContentRequest` will be null... because this UmbracoContext hasn't had a `PublishedContentRequest` because it's *not* a request with published content. You can access the `RoutingContext` directly on the UmbracoContext: `context.RoutingContext`

**Comment by kipusoep** [comment] 2015-12-18 10:33
```context.PublishedContentRequest``` is not null, but using ```context.RoutingContext``` gives another exception:

<pre>
[NullReferenceException: Object reference not set to an instance of an object.]
   Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.DetermineRouteById(UmbracoContext umbracoContext, Boolean preview, Int32 contentId) +61
   Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.GetRouteById(UmbracoContext umbracoContext, Boolean preview, Int32 contentId) +86
   Umbraco.Web.Routing.DefaultUrlProvider.GetUrl(UmbracoContext umbracoContext, Int32 id, Uri current, UrlProviderMode mode) +96
   Umbraco.Web.Routing.<>c__DisplayClass3.<GetUrl>b__0(IUrlProvider provider) +28
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +58
   System.Linq.Enumerable.FirstOrDefault(IEnumerable`1 source, Func`2 predicate) +94
   Umbraco.Web.Routing.UrlProvider.GetUrl(Int32 id, Uri current, UrlProviderMode mode) +169
   Umbraco.Web.Routing.UrlProvider.GetUrl(Int32 id) +15
   InfoCaster.Umbraco.UrlTracker.Helpers.UmbracoHelper.GetUrl(Int32 nodeId) in D:\kipusoep\Documents\GitHub\UrlTracker\Helpers\UmbracoHelper.cs:145
   InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.LoadUrlTrackerMatchesFromDatabase(HttpRequest request, String urlWithoutQueryString, Boolean urlHasQueryString, String shortestUrl, Int32 rootNodeId, String& redirectUrl, Nullable`1& redirectHttpCode, Boolean& redirectPassThroughQueryString) in D:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:412
   InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.UrlTrackerDo(String callingEventName, Boolean ignoreHttpStatusCode) in D:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:199
   InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.context_EndRequest(Object sender, EventArgs e) in D:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:81
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69
</pre>

Again the exception occurs with this line:
```var domainHelper = new DomainHelper(umbracoContext.Application.Services.DomainService);```
This time it's inside ```Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.DetermineRouteById(UmbracoContext umbracoContext, bool preview, int contentId)``` on line 125.
Again ```umbracoContext.Application``` is null.

**Comment by Shazwazza** [comment] 2015-12-21 09:11
Ah right. Well if there's any conciliation, that won't occur in 7.4. We dispose and set a few referenced items to null on the UmbracoContext and some sub objects because at one point in time there was a fear of a potential memory leak with HttpContext, or objects not being GC'd that had references to old HttpContexts. Some of these null settings will still occur, but not ones where there is a reference to an application wide singleton such as the ApplicationContext.

In the meantime, the exception is coming from here:
`InfoCaster.Umbraco.UrlTracker.Helpers.UmbracoHelper.GetUrl` 
Which I can see does this:
https://github.com/kipusoep/UrlTracker/blob/master/Helpers/UmbracoHelper.cs#L135

which is not good since `library` is legacy and should only ever be used for XSLT. This will also *always* use singleton access because you are using statics. As a best practice, please try to shy away from using statics and Singletons whenever possible, that will just cause you issues in the long run.

Instead, do something like this:

```
//don't set the boolean for replaceContext since you don't need to use the singleton
using (var umbCtx = UmbracoContext.EnsureUmbracoContext(....)) {
     var helper = new UmbracoHelper(umbCtx)
     var url = helper.UrlProvider.GetUrl(...);
     //do stuff ....
}
```

**Comment by kipusoep** [comment] 2015-12-22 23:12
Nice work, just tested with Umbraco 7.4.0 beta and it's working again :-)
So my advice is to skip 7.3 or upgrade to 7.4!

Ps. I know it's legacy, but I had to support legacy versions too, so I'm not sure what can be refactored at the moment and what can't. Thanks for your help @Shazwazza

**Closed by kipusoep** 2015-12-22 23:12 UTC

**Comment by Shazwazza** [comment] 2015-12-22 23:46
That snippet I posted will work for 7.3 so I'm sure you could support it if you wanted. 

I know a lot of devs have a single build to support multiple versions... But I don't really see the point. These are my own personal opinions: Just release a new major version of your project with a dependency on the latest version of Umbraco that you want to use/support. People can still use your older versions, and its easy to release another minor version if you need to, since everything is source controlled (and tagged accordingly). It also leaves you with less headaches, nicer code, less legacy code to support, as well as promoting people to use newer versions of Umbraco. This is what I do with my projects and people have never complained about it. If a new version of Umbraco comes out, and I want to use a new feature or bit of code, release a new major version with a new Umbraco dependency and document breaking changes . 

Anyways, those are my opinion ;) have a great xmas!!!

**Comment by kipusoep** [comment] 2015-12-22 23:51
Hmm I really don't know why I got that NullReferences then, I tried 7.3 multiple times and got the same Exception over and over again.

Anyway, I agree with you about versioning. Though I don't think it's worth it for the Url Tracker (functionality migrating to the core soonish?).
Since Umbraco is much easier to upgrade nowadays (NuGet) it's easier to work as you described.

You have a great Christmas too :-)

**Comment by Shazwazza** [comment] 2016-01-23 11:43
Some updates today:

* Without changing any of UrlTracker's code, it will now work in 7.3.6

**Comment by Shazwazza** [comment] 2016-01-23 11:47
I would strongly recommend that you get the latest Umbraco 7.3.6 nightly when it's built and verify that it all works as you expect before the actual 7.3.6 release next week.

**Comment by kipusoep** [comment] 2016-01-23 11:49
Thanks @Shazwazza, that's great news! Appreciate it!
What you're saying sounds like a good plan to me. But how about the plan to integrate the basics of the Url Tracker functionality into the core? That's on the roadmap for v7.soon isn't it?
When 7.3.6 nightly is available I'll do some testing.

**Comment by Shazwazza** [comment] 2016-01-23 12:27
Yes that is a goal for 7.x. This will be a more basic approach however, it will track all changed Umbraco Urls but as far as static file redirects or other non-managed Ursl, that functionality will most likely remain outside of Umbraco core.

**Comment by kipusoep** [comment] 2016-01-23 12:56
Ok, I will follow your advices and create a new major version :-) Thanks again!

**Comment by kipusoep** [comment] 2016-01-23 13:14
So I created a v4 branch, just a quick question @Shazwazza; what v7 branch would you require for a new major version of this tool?

**Comment by Shazwazza** [comment] 2016-01-23 13:20
Remove all your Umbraco references, delete your lib folder, change your target framework to 4.5.2, then run `Install-Package UmbracoCms.Core`. Now you are targeting a minimum of 7.3.5
... So you'll need to wait until 7.3.6 is out to ew target. Or you can build the 7.3.6 nuget from the 7.3.6 branch.

**Comment by kipusoep** [comment] 2016-01-23 13:22
I did, but I'm just thinking about targeting 7.0, 7.1, 7.2 or 7.3.6.
Isn't 7.3.6 a bit too high? Lots of projects are lower then 7.3.6 or even 7.3 and they won't be able to update Url Tracker anymore.

**Comment by Shazwazza** [comment] 2016-01-23 16:15
Then people can upgrade if they want to use new features. It really depends on the lowest APIs you want to use. You can stay stuck using the legacy APIs if you want but it's your choice and I don't recommend that. I keep articulate running on recent versions of Umbraco because I use recent APIs. Nobody complains, they just upgrade to the latest Umbraco version. When people install new versions of Umbraco, they don't install 7.1 or whatever, they install the latest version. I don't understand the reason why developers are so determined to support older versions of Umbraco. You can release a new major version of your product when you put a dependency on a newer Umbraco version... And move forward with your product.

**Comment by kipusoep** [comment] 2016-01-23 16:17
Yeah I think you're right, developers tend to support older versions for a long time, including me.
I installed Umbraco.Core v7.3.5 just now :+1:

**Comment by kipusoep** [comment] 2016-01-25 09:47
Just tested v7.3.6 and the Exception is gone + the redirect works :-)

**Comment by Shazwazza** [comment] 2016-01-25 12:21
Good news. Was there ever an Umbraco issue created for this ?

**Comment by kipusoep** [comment] 2016-01-25 12:46
No not that I know of...
