### ISSUE TITLE
Redirect not working after page rename only works if forced box is ticked V7.3

### ISSUE THREAD

**Issue by mcgawn** [kipusoep/UrlTracker#98] opened 2015-10-07 12:12 UTC
![image](https://cloud.githubusercontent.com/assets/1831895/10337007/d08efb48-6cf4-11e5-8fa9-59d9f4b63634.png)

I have the app installed but i am getting the error above when a page name is changed, the redirect isnt working, but i have noticed if i add a check to the forced box it work.

What could this be?

**Comment by nul800sebastiaan** [comment] 2015-10-14 11:44
This is a duplicate of https://github.com/kipusoep/UrlTracker/issues/90

**Comment by kipusoep** [comment] 2015-11-17 08:14
Could you try with [3.10-rc](https://www.nuget.org/packages/UrlTracker/3.10.0-rc)?

**Closed by kipusoep** 2015-11-17 08:14 UTC
